# Generated by Django 5.0.4 on 2024-05-03 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.cart'),
        ),
    ]
